server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource_management_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serviceTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 6000
mybatis:
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      #operations-sorter: order
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'userManagement'
        paths-to-match: '/**'
        packages-to-scan: selab.desktop.resource_management.userManagement
      - group: 'item Management'
        paths-to-match: '/**'
        packages-to-scan: selab.desktop.resource_management.itemManagement
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
selab:
  handle:
    # 配置username的管理员负责处理申请
    apply: admain
# 日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'
