logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    selab.desktop.resource_management.fundManagement.controller.FundsController: debug
    selab.desktop.resource_management.ResourceManagementPlatformApplication: warn

server:
  port: 9090
  server-header: Access-Control-Allow-Origin:*

spring:
  application:
    name: resource_management_platform
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&CharacterEncoding=utf-8&userSSL=false
    username: root
    password: 159753
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
